---
- name: "Verify HAProxy installation"
  block:
    - name: "Get HAProxy service current state"
      register: add_haproxy_bdd_confs__service_status
      failed_when: not (add_haproxy_bdd_confs__service_status.status.ActiveState == 'active' or add_haproxy_bdd_confs__service_status.status.ActiveState == 'failed')
      ansible.builtin.systemd:
        name: "haproxy"

    - name: "Check if conf path directory exist"
      register: host_working_folder
      failed_when: not host_working_folder.stat.exists
      ansible.builtin.stat:
        path: "{{ add_haproxy_bdd_confs__confs_path }}"

- name: "Create HAProxy sub conf files"
  loop: "{{ add_haproxy_bdd_confs__configurations }}"
  loop_control:
    loop_var: configuration
  notify: "Restart HAProxy"
  vars:
    configuration_fullchain: "{{ add_haproxy_bdd_confs__ssl_path }}/{{ configuration.name }}-fullchain.pem"
  ansible.builtin.template:
    src: "templates/conf.cfg.j2"
    dest: "{{ add_haproxy_bdd_confs__confs_path }}/{{ configuration.name }}.cfg"
    lstrip_blocks: yes
    owner: "{{ add_haproxy_bdd_confs__haproxy_user }}"
    group: "{{ add_haproxy_bdd_confs__haproxy_group }}"
    mode: "0700"
