---
- name: "Converge"
  hosts: "local"
  tasks:

    - name: "Include labocbz.add_haproxy_bdd_confs"
      tags:
        - "labocbz.add_haproxy_bdd_confs"
      vars:
        add_haproxy_bdd_confs__confs_path: "{{ inv_add_haproxy_bdd_confs__confs_path }}"
        add_haproxy_bdd_confs__configurations: "{{ inv_add_haproxy_bdd_confs__configurations }}"
      ansible.builtin.include_role:
        name: "labocbz.add_haproxy_bdd_confs"
